language: node_js

node_js:
  - "6"

install:
  - npm install

script: npm run mix:production

after_success: npm prune --production

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy
  on:
    branch: master

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"
